ARG PHP_FPM_VERSION=8.1.19-fpm
FROM php:${PHP_FPM_VERSION}

RUN yes | pecl install grpc \
    && docker-php-ext-enable grpc

RUN \
    set -eux \
    \
    && find "$(php-config --extension-dir)" -name '*.so' -type f -exec strip --strip-all {} \;
