ARG PHP_FPM_VERSION=8.1.19-fpm
FROM php:${PHP_FPM_VERSION}

# Install packages required to compile php extensions
RUN apt-get update && apt-get install -y \
    zip \
    curl \
    unzip \
    libicu-dev \
    libbz2-dev \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libmcrypt-dev \
    libreadline-dev \
    libfreetype6-dev \
    g++

# Compile and install Common PHP Extensions
RUN docker-php-ext-install \
    bz2 \
    intl \
    soap \
    iconv \
    bcmath \
    opcache \
    calendar \
    pdo_mysql \
    gd

RUN \
    set -eux \
    \
    && find "$(php-config --extension-dir)" -name '*.so' -type f -exec strip --strip-all {} \;
