name: centos8-git ci

on:
  push:
    tags:
      - 'centos-git/*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Get the version
        id: get_version
        # Will take position 4 from $GITHUB_REF as values are refs/tags/{tagname}
        # and tag name is php/
        run: echo $GITHUB_REF && echo VERSION=$(echo $GITHUB_REF | cut -d / -f 4) >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository_owner }}/centos8_git:latest,${{ github.repository_owner }}/centos8_git:${{ steps.get_version.outputs.VERSION }} 
          build-args: |
            CENTOS_VERSION=8
            GIT_VERSION=${{ steps.get_version.outputs.VERSION }}
