name: centos8-git ci

on:
  push:
    tags:
      - 'centos-git/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Get the git version
        id: get_version
        # Will take position 4 from $GITHUB_REF as values are refs/tags/{tagname}
        # and tag name is php/
        run: echo $GITHUB_REF && echo VERSION=$(echo $GITHUB_REF | cut -d / -f 4) >> $GITHUB_OUTPUT
      -
        name: Build centos 7 version
        run: |
          docker buildx build \
          --build-arg="CENTOS_VERSION=7" \
          --build-arg="GIT_VERSION=${{ steps.get_version.outputs.VERSION }}" \
          --platform linux/amd64,linux/arm64 \
          --tag ${{ github.repository_owner }}/centos7_git:latest \
          --tag ${{ github.repository_owner }}/centos7_git:${{ steps.get_version.outputs.VERSION }}  \
          --file centos/git/Dockerfile --push .
      -
        name: Build centos 8 version
        run: |
          docker buildx build \
          --build-arg="CENTOS_VERSION=8" \
          --build-arg="GIT_VERSION=${{ steps.get_version.outputs.VERSION }}" \
          --platform linux/amd64,linux/arm64 \
          --tag ${{ github.repository_owner }}/centos8_git:latest \
          --tag ${{ github.repository_owner }}/centos8_git:${{ steps.get_version.outputs.VERSION }}  \
          --file centos/git/Dockerfile --push .
