name: centos-golang ci

on:
  push:
    tags:
      - 'centos-golang/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - 
        name: Get the golang version
        id: get_version
        # Will take position 4 from $GITHUB_REF as values are refs/tags/{tagname}
        # and tag name is php/
        run: echo $GITHUB_REF && echo VERSION=$(echo $GITHUB_REF | cut -d / -f 4) >> $GITHUB_OUTPUT
      -
        name: Build centos 7 version
        run: |
          docker buildx build \
          --build-arg="CENTOS_VERSION=7" \
          --build-arg="GOLANG_VERSION=${{ steps.get_version.outputs.VERSION }}" \
          --platform linux/amd64,linux/arm64 \
          -t ${{ github.repository_owner }}/centos7_golang:latest,${{ github.repository_owner }}/centos7_golang:${{ steps.get_version.outputs.VERSION }}  \
          --file centos/golang/Dockerfile --push .
      -
        name: Build centos 8 version
        run: |
          docker buildx build \
          --build-arg="CENTOS_VERSION=8" \
          --build-arg="GOLANG_VERSION=${{ steps.get_version.outputs.VERSION }}" \
          --platform linux/amd64,linux/arm64 \
          -t ${{ github.repository_owner }}/centos8_golang:latest,${{ github.repository_owner }}/centos8_golang:${{ steps.get_version.outputs.VERSION }}  \
          --file centos/golang/Dockerfile --push .
